// // Set ALL_WHITE as default effect
// #define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_ALL_WHITE
// #define RGB_MATRIX_DEFAULT_HUE  0
// #define RGB_MATRIX_DEFAULT_SAT  0
// #define RGB_MATRIX_DEFAULT_VAL  255
// #define RGB_MATRIX_DEFAULT_SPD  0